-- ============================================================================
-- Seed — libraries and settings.
--
-- Values lifted verbatim from design-reference/quoting-tool/app/data.js so the
-- ported screens behave identically to the prototype. Idempotent: safe to
-- re-run.
--
-- Does NOT seed clients or quotes. The prototype's sample quotes are demo
-- fixtures, not business records.
-- ============================================================================

-- ── Pipeline stages ─────────────────────────────────────────────────────────
insert into public.pipeline_stages (id, label, sort, is_terminal) values
  ('enquiry',      'Enquiry',           1, false),
  ('qualified',    'Qualified',         2, false),
  ('visit_booked', 'Site visit booked', 3, false),
  ('quoted',       'Quoted',            4, false),
  ('won',          'Won',               5, true),
  ('lost',         'Lost',              6, true)
on conflict (id) do update
  set label = excluded.label,
      sort = excluded.sort,
      is_terminal = excluded.is_terminal;

-- ── Settings ────────────────────────────────────────────────────────────────
-- payment_terms is an explicit PLACEHOLDER. For NSW licensed building work the
-- wording must be owner-supplied or professionally reviewed — never generated.
insert into public.settings (
  id, business_name, legal_name, owner_name, licence_no, abn, acn,
  phone, email, site, address,
  gst_registered, gst_rate, deposit_enabled, deposit_pct,
  default_margin_pct, default_valid_days, margin_floor_pct, follow_up_days,
  payment_terms
) values (
  1,
  'Australian Roofing Contractors',
  'Australian Roofing Contractors Pty Ltd',
  'John Reardon',
  '245723C',
  '59 148 109 399',
  '148 109 399',
  '(02) 8005 4321',
  'info@roofing.sydney',
  'roofing.theprofitplatform.com.au',
  'Sydney, NSW',
  false, 10, false, 10,
  20, 30, 15, 7,
  '[ Payment terms placeholder — replace before sending. ] '
  'Enter your own payment, deposit and warranty terms here. For NSW licensed '
  'building work these should be supplied by the owner or professionally reviewed '
  '(e.g. against the NSW Home Building Act) — not generated by this tool. '
  'Edit this text in Settings → Business → Payment terms.'
)
on conflict (id) do nothing;

-- ── Price book (14 items) ───────────────────────────────────────────────────
insert into public.price_book (kind, category, description, unit, unit_cost_cents)
select * from (values
  ('material', 'Sheet roofing',    'Colorbond Trimdek sheets',          'm2',  4200::bigint),
  ('material', 'Sheet roofing',    'Colorbond Klip-Lok 700',            'm2',  5400),
  ('material', 'Sheet roofing',    'Anticon blanket insulation 60mm',   'm2',  1350),
  ('material', 'Sheet roofing',    'Steel top-hat battens',             'm',    850),
  ('material', 'Rainwater goods',  'Colorbond quad gutter',             'm',   1850),
  ('material', 'Rainwater goods',  'Downpipe 90mm + brackets',          'm',   1450),
  ('material', 'Rainwater goods',  'Gutter guard — aluminium mesh',     'm',   2200),
  ('material', 'Tiles & pointing', 'Replacement terracotta tiles',      'ea',  1400),
  ('material', 'Tiles & pointing', 'Flexible pointing & bedding sand',  'ea', 18000),
  ('material', 'Restoration',      'Roof membrane & primer (3-coat)',   'm2',  1250),
  ('labour',   'Labour',           'Roofer — standard rate',            'hr',  9500),
  ('labour',   'Labour',           'Tile roof removal & disposal',      'hr',  9500),
  ('labour',   'Access',           'Scaffold hire & erection',          'ea', 285000),
  ('labour',   'Access',           'Cherry picker / EWP day hire',      'day', 78000)
) as v(kind, category, description, unit, unit_cost_cents)
where not exists (
  select 1 from public.price_book pb where pb.description = v.description
);

-- ── Clause library (11 snippets) ────────────────────────────────────────────
insert into public.snippets (kind, text, is_default, sort)
select * from (values
  ('exclusion', 'We are not responsible for electrical work.', true, 1),
  ('exclusion', 'We are not responsible for structural or carpentry issues.', true, 2),
  ('exclusion', 'Latent (pre-existing, concealed) conditions are excluded and, if found, will be quoted as a variation.', true, 3),
  ('exclusion', 'Existing roof falls are not corrected; we remove and replace to existing falls and capacity.', true, 4),
  ('exclusion', 'Hydraulic/structural engineering, if required, must be engaged separately.', true, 5),
  ('exclusion', 'Asbestos removal is excluded; if asbestos is identified, a licensed removalist will be engaged separately.', false, 6),
  ('inclusion', 'Supply of all materials specified in this quote.', true, 1),
  ('inclusion', 'Removal and lawful disposal of all roofing debris.', true, 2),
  ('inclusion', 'Site left clean and tidy on completion.', true, 3),
  ('inclusion', '10-year workmanship warranty on installation.', false, 4),
  ('inclusion', 'All work carried out to AS 1562.1 and manufacturer specifications.', false, 5)
) as v(kind, text, is_default, sort)
where not exists (
  select 1 from public.snippets s where s.text = v.text
);

-- ── Job templates (3) ───────────────────────────────────────────────────────
insert into public.job_templates (label, sub, icon, roof_type, valid_days, margin_pct, show_breakdown, notes, line_items, sort)
select * from (values
  (
    'Full re-roof',
    'Strip tiles, new sheets, insulation & battens',
    'layers',
    'Colorbond — full re-roof',
    30, 22::numeric, true,
    'Remove existing roof and replace with new Colorbond sheeting. Includes new sarking and battens.',
    '[
      {"kind":"material","description":"Colorbond Trimdek sheets","qty":180,"unit":"m2","unit_cost_cents":4200},
      {"kind":"material","description":"Anticon blanket insulation 60mm","qty":180,"unit":"m2","unit_cost_cents":1350},
      {"kind":"material","description":"Steel top-hat battens","qty":234,"unit":"m","unit_cost_cents":850},
      {"kind":"material","description":"Ridge capping, barge & flashings","qty":1,"unit":"ea","unit_cost_cents":142000},
      {"kind":"material","description":"Fasteners, sealant & sundries","qty":1,"unit":"ea","unit_cost_cents":68000},
      {"kind":"labour","description":"Tile roof removal & disposal","qty":24,"unit":"hr","unit_cost_cents":9500},
      {"kind":"labour","description":"Sheet installation (2 crew)","qty":56,"unit":"hr","unit_cost_cents":9500},
      {"kind":"labour","description":"Scaffold hire & erection","qty":1,"unit":"ea","unit_cost_cents":285000}
    ]'::jsonb,
    1
  ),
  (
    'Gutter replacement',
    'New gutters, downpipes & gutter guard',
    'corner-down-right',
    'Gutter & downpipe replacement',
    30, 18, true,
    'Replace existing gutters and downpipes. Colour to be confirmed.',
    '[
      {"kind":"material","description":"Colorbond quad gutter","qty":40,"unit":"m","unit_cost_cents":1850},
      {"kind":"material","description":"Downpipes 90mm + brackets","qty":16,"unit":"m","unit_cost_cents":1450},
      {"kind":"material","description":"Gutter guard — aluminium mesh","qty":40,"unit":"m","unit_cost_cents":2200},
      {"kind":"labour","description":"Removal & installation","qty":14,"unit":"hr","unit_cost_cents":9500}
    ]'::jsonb,
    2
  ),
  (
    'Leak repair',
    'Find & fix, ridge re-bed, tile swaps',
    'droplets',
    'Leak repair & ridge re-bedding',
    14, 25, false,
    'Investigate and repair active leak. Re-bed and re-point ridge capping as required.',
    '[
      {"kind":"material","description":"Flexible pointing & bedding sand","qty":1,"unit":"ea","unit_cost_cents":18000},
      {"kind":"material","description":"Replacement terracotta tiles","qty":10,"unit":"ea","unit_cost_cents":1400},
      {"kind":"labour","description":"Leak detection & repair","qty":6,"unit":"hr","unit_cost_cents":9500},
      {"kind":"labour","description":"Ridge re-bed & re-point","qty":6,"unit":"hr","unit_cost_cents":9500}
    ]'::jsonb,
    3
  )
) as v(label, sub, icon, roof_type, valid_days, margin_pct, show_breakdown, notes, line_items, sort)
where not exists (
  select 1 from public.job_templates t where t.label = v.label
);
