/* Australian Roofing Contractors — sample data.
   Money stored as INTEGER CENTS. Formatted to AUD at display time. */

window.ARC_BUSINESS = {
  business_name: "Australian Roofing Contractors",
  legal_name: "Australian Roofing Contractors Pty Ltd",
  owner_name: "John Reardon",
  licence_no: "245723C",
  abn: "59 148 109 399",
  acn: "148 109 399",
  phone: "(02) 8005 4321",
  email: "info@roofing.sydney",
  site: "roofing.theprofitplatform.com.au",
  address: "Sydney, NSW",
  gst_registered: false,
  deposit_enabled: false,
  deposit_pct: 10,
  logo_data: "",
  default_margin_pct: 20,
  default_valid_days: 30,
  margin_floor_pct: 15,
  follow_up_days: 7,
  // PLACEHOLDER — owner-supplied / professionally-reviewed wording goes here.
  // Do NOT ship AI-generated payment or warranty terms on licensed building work.
  payment_terms:
    "[ Payment terms placeholder — replace before sending. ] " +
    "Enter your own payment, deposit and warranty terms here. For NSW licensed " +
    "building work these should be supplied by the owner or professionally reviewed " +
    "(e.g. against the NSW Home Building Act) — not generated by this tool. " +
    "Edit this text in Settings → Business → Payment terms.",
};

/* Reusable price book — tap to add into a quote. */
window.ARC_PRICE_BOOK = [
  { id: "p1", kind: "material", category: "Sheet roofing", description: "Colorbond Trimdek sheets", unit: "m2", unit_cost_cents: 4200 },
  { id: "p2", kind: "material", category: "Sheet roofing", description: "Colorbond Klip-Lok 700", unit: "m2", unit_cost_cents: 5400 },
  { id: "p3", kind: "material", category: "Sheet roofing", description: "Anticon blanket insulation 60mm", unit: "m2", unit_cost_cents: 1350 },
  { id: "p4", kind: "material", category: "Sheet roofing", description: "Steel top-hat battens", unit: "m", unit_cost_cents: 850 },
  { id: "p5", kind: "material", category: "Rainwater goods", description: "Colorbond quad gutter", unit: "m", unit_cost_cents: 1850 },
  { id: "p6", kind: "material", category: "Rainwater goods", description: "Downpipe 90mm + brackets", unit: "m", unit_cost_cents: 1450 },
  { id: "p7", kind: "material", category: "Rainwater goods", description: "Gutter guard — aluminium mesh", unit: "m", unit_cost_cents: 2200 },
  { id: "p8", kind: "material", category: "Tiles & pointing", description: "Replacement terracotta tiles", unit: "ea", unit_cost_cents: 1400 },
  { id: "p9", kind: "material", category: "Tiles & pointing", description: "Flexible pointing & bedding sand", unit: "ea", unit_cost_cents: 18000 },
  { id: "p10", kind: "material", category: "Restoration", description: "Roof membrane & primer (3-coat)", unit: "m2", unit_cost_cents: 1250 },
  { id: "p11", kind: "labour", category: "Labour", description: "Roofer — standard rate", unit: "hr", unit_cost_cents: 9500 },
  { id: "p12", kind: "labour", category: "Labour", description: "Tile roof removal & disposal", unit: "hr", unit_cost_cents: 9500 },
  { id: "p13", kind: "labour", category: "Access", description: "Scaffold hire & erection", unit: "ea", unit_cost_cents: 285000 },
  { id: "p14", kind: "labour", category: "Access", description: "Cherry picker / EWP day hire", unit: "day", unit_cost_cents: 78000 },
];

/* Quote templates — seeded from the shape of real quotes. Quantities are
   starting points the contractor edits after a site visit. */
window.ARC_TEMPLATES = [
  {
    id: "t_reroof", label: "Full re-roof", icon: "layers",
    sub: "Strip tiles, new sheets, insulation & battens",
    roof_type: "Colorbond — full re-roof", valid_days: 30, margin_pct: 22, show_breakdown: true,
    notes: "Remove existing roof and replace with new Colorbond sheeting. Includes new sarking and battens.",
    line_items: [
      { kind: "material", description: "Colorbond Trimdek sheets", qty: 180, unit: "m2", unit_cost_cents: 4200 },
      { kind: "material", description: "Anticon blanket insulation 60mm", qty: 180, unit: "m2", unit_cost_cents: 1350 },
      { kind: "material", description: "Steel top-hat battens", qty: 234, unit: "m", unit_cost_cents: 850 },
      { kind: "material", description: "Ridge capping, barge & flashings", qty: 1, unit: "ea", unit_cost_cents: 142000 },
      { kind: "material", description: "Fasteners, sealant & sundries", qty: 1, unit: "ea", unit_cost_cents: 68000 },
      { kind: "labour", description: "Tile roof removal & disposal", qty: 24, unit: "hr", unit_cost_cents: 9500 },
      { kind: "labour", description: "Sheet installation (2 crew)", qty: 56, unit: "hr", unit_cost_cents: 9500 },
      { kind: "labour", description: "Scaffold hire & erection", qty: 1, unit: "ea", unit_cost_cents: 285000 },
    ],
  },
  {
    id: "t_gutter", label: "Gutter replacement", icon: "corner-down-right",
    sub: "New gutters, downpipes & gutter guard",
    roof_type: "Gutter & downpipe replacement", valid_days: 30, margin_pct: 18, show_breakdown: true,
    notes: "Replace existing gutters and downpipes. Colour to be confirmed.",
    line_items: [
      { kind: "material", description: "Colorbond quad gutter", qty: 40, unit: "m", unit_cost_cents: 1850 },
      { kind: "material", description: "Downpipes 90mm + brackets", qty: 16, unit: "m", unit_cost_cents: 1450 },
      { kind: "material", description: "Gutter guard — aluminium mesh", qty: 40, unit: "m", unit_cost_cents: 2200 },
      { kind: "labour", description: "Removal & installation", qty: 14, unit: "hr", unit_cost_cents: 9500 },
    ],
  },
  {
    id: "t_leak", label: "Leak repair", icon: "droplets",
    sub: "Find & fix, ridge re-bed, tile swaps",
    roof_type: "Leak repair & ridge re-bedding", valid_days: 14, margin_pct: 25, show_breakdown: false,
    notes: "Investigate and repair active leak. Re-bed and re-point ridge capping as required.",
    line_items: [
      { kind: "material", description: "Flexible pointing & bedding sand", qty: 1, unit: "ea", unit_cost_cents: 18000 },
      { kind: "material", description: "Replacement terracotta tiles", qty: 10, unit: "ea", unit_cost_cents: 1400 },
      { kind: "labour", description: "Leak detection & repair", qty: 6, unit: "hr", unit_cost_cents: 9500 },
      { kind: "labour", description: "Ridge re-bed & re-point", qty: 6, unit: "hr", unit_cost_cents: 9500 },
    ],
  },
];

window.ARC_CLIENTS = [
  { id: "c1", name: "Margaret Chen", phone: "0412 884 220", email: "m.chen@bigpond.com", property_address: "14 Wattle Street, Marrickville NSW 2204" },
  { id: "c2", name: "David Nguyen", phone: "0438 117 902", email: "david.nguyen@gmail.com", property_address: "8 Hillcrest Avenue, Hurstville NSW 2220" },
  { id: "c3", name: "Priya & Sam Sharma", phone: "0401 556 318", email: "priya.sharma@outlook.com", property_address: "22 Beach Road, Cronulla NSW 2230" },
  { id: "c4", name: "Robert Kostas", phone: "0407 339 145", email: "rkostas@iinet.net.au", property_address: "5 Jersey Road, Strathfield NSW 2135" },
  { id: "c5", name: "Holland Property Group", phone: "(02) 9555 7788", email: "maintenance@hollandpg.com.au", property_address: "Unit 1–6, 40 Forsyth Street, Glebe NSW 2037" },
  { id: "c6", name: "Aisha Rahman", phone: "0423 887 661", email: "", property_address: "11 Lewis Street, Epping NSW 2121" },
];

window.ARC_SNIPPETS = [
  { id: "ex1", kind: "exclusion", is_default: true, text: "We are not responsible for electrical work." },
  { id: "ex2", kind: "exclusion", is_default: true, text: "We are not responsible for structural or carpentry issues." },
  { id: "ex3", kind: "exclusion", is_default: true, text: "Latent (pre-existing, concealed) conditions are excluded and, if found, will be quoted as a variation." },
  { id: "ex4", kind: "exclusion", is_default: true, text: "Existing roof falls are not corrected; we remove and replace to existing falls and capacity." },
  { id: "ex5", kind: "exclusion", is_default: true, text: "Hydraulic/structural engineering, if required, must be engaged separately." },
  { id: "ex6", kind: "exclusion", is_default: false, text: "Asbestos removal is excluded; if asbestos is identified, a licensed removalist will be engaged separately." },
  { id: "in1", kind: "inclusion", is_default: true, text: "Supply of all materials specified in this quote." },
  { id: "in2", kind: "inclusion", is_default: true, text: "Removal and lawful disposal of all roofing debris." },
  { id: "in3", kind: "inclusion", is_default: true, text: "Site left clean and tidy on completion." },
  { id: "in4", kind: "inclusion", is_default: false, text: "10-year workmanship warranty on installation." },
  { id: "in5", kind: "inclusion", is_default: false, text: "All work carried out to AS 1562.1 and manufacturer specifications." },
];

/* Pre-built quotes. line_items: {kind, description, qty, unit, unit_cost_cents}
   inclusions/exclusions: resolved text arrays stored on the quote.
   Dates are relative to "today" so follow-up / expiry nudges demo correctly. */
const _d = (daysAgo) => new Date(Date.now() - daysAgo * 86400000).toISOString().slice(0, 10);
window.ARC_QUOTES = [
  {
    id: "q7", quote_number: "Q-2026-0007", client_id: "c3", status: "sent",
    roof_type: "Colorbond Trimdek — full re-roof", valid_days: 30,
    show_breakdown: true, margin_pct: 22, gst_enabled: false, pdf_layout: "modern",
    notes: "Remove existing concrete tile roof and replace with Colorbond Trimdek (Surfmist). Includes new sarking and battens. Two-storey, scaffold required.",
    created_at: _d(6), sent_at: _d(5), viewed_at: _d(4),
    photos: [{ id: "ph1", hue: 24, caption: "Existing tile roof — south face" }, { id: "ph2", hue: 210, caption: "Rusted valley above ensuite" }, { id: "ph3", hue: 150, caption: "Two-storey access — scaffold side" }], include_photos: true,
    line_items: [
      { kind: "material", description: "Colorbond Trimdek sheets — Surfmist", qty: 188, unit: "m2", unit_cost_cents: 4200 },
      { kind: "material", description: "Anticon blanket insulation 60mm", qty: 188, unit: "m2", unit_cost_cents: 1350 },
      { kind: "material", description: "Steel top-hat battens", qty: 240, unit: "m", unit_cost_cents: 850 },
      { kind: "material", description: "Ridge capping, barge & flashings", qty: 1, unit: "ea", unit_cost_cents: 142000 },
      { kind: "material", description: "Fasteners, sealant & sundries", qty: 1, unit: "ea", unit_cost_cents: 68000 },
      { kind: "labour", description: "Tile roof removal & disposal", qty: 24, unit: "hr", unit_cost_cents: 9500 },
      { kind: "labour", description: "Sheet installation (2 crew)", qty: 56, unit: "hr", unit_cost_cents: 9500 },
      { kind: "labour", description: "Scaffold hire & erection", qty: 1, unit: "ea", unit_cost_cents: 285000 },
    ],
    inclusions: ["Supply of all materials specified in this quote.", "Removal and lawful disposal of all roofing debris.", "Site left clean and tidy on completion.", "10-year workmanship warranty on installation."],
    exclusions: ["We are not responsible for electrical work.", "We are not responsible for structural or carpentry issues.", "Latent (pre-existing, concealed) conditions are excluded and, if found, will be quoted as a variation.", "Hydraulic/structural engineering, if required, must be engaged separately."],
    custom_clauses: [],
  },
  {
    id: "q6", quote_number: "Q-2026-0006", client_id: "c1", status: "draft",
    roof_type: "Gutter & downpipe replacement", valid_days: 30,
    show_breakdown: true, margin_pct: 18, gst_enabled: false,
    notes: "Replace perished quad gutters and downpipes to single-storey weatherboard. Colour: Monument.",
    created_at: _d(2), sent_at: null,
    line_items: [
      { kind: "material", description: "Colorbond quad gutter — Monument", qty: 46, unit: "m", unit_cost_cents: 1850 },
      { kind: "material", description: "Downpipes 90mm + brackets", qty: 18, unit: "m", unit_cost_cents: 1450 },
      { kind: "material", description: "Gutter guard — aluminium mesh", qty: 46, unit: "m", unit_cost_cents: 2200 },
      { kind: "labour", description: "Removal & installation", qty: 16, unit: "hr", unit_cost_cents: 9500 },
    ],
    inclusions: ["Supply of all materials specified in this quote.", "Removal and lawful disposal of all roofing debris.", "Site left clean and tidy on completion."],
    exclusions: ["We are not responsible for electrical work.", "We are not responsible for structural or carpentry issues.", "Existing roof falls are not corrected; we remove and replace to existing falls and capacity."],
    custom_clauses: [],
  },
  {
    id: "q5", quote_number: "Q-2026-0005", client_id: "c4", status: "sent",
    roof_type: "Leak repair & ridge re-bedding", valid_days: 14,
    show_breakdown: false, margin_pct: 25, gst_enabled: false,
    notes: "Investigate and repair active leak above ensuite. Re-bed and re-point ridge capping along southern hip.",
    created_at: _d(11), sent_at: _d(11), viewed_at: _d(10),
    line_items: [
      { kind: "material", description: "Flexible pointing & bedding sand", qty: 1, unit: "ea", unit_cost_cents: 18000 },
      { kind: "material", description: "Replacement terracotta tiles", qty: 12, unit: "ea", unit_cost_cents: 1400 },
      { kind: "labour", description: "Leak detection & repair", qty: 6, unit: "hr", unit_cost_cents: 9500 },
      { kind: "labour", description: "Ridge re-bed & re-point", qty: 7, unit: "hr", unit_cost_cents: 9500 },
    ],
    inclusions: ["Supply of all materials specified in this quote.", "Site left clean and tidy on completion."],
    exclusions: ["Latent (pre-existing, concealed) conditions are excluded and, if found, will be quoted as a variation.", "We are not responsible for structural or carpentry issues."],
    custom_clauses: ["Repair carries a 12-month warranty against recurrence at the repaired locations."],
  },
  {
    id: "q4", quote_number: "Q-2026-0004", client_id: "c2", status: "sent",
    roof_type: "Roof restoration & repaint", valid_days: 30,
    show_breakdown: true, margin_pct: 20, gst_enabled: false,
    notes: "High-pressure clean, re-bed & re-point ridges, replace broken tiles, apply 3-coat membrane. Colour: Wallaby.",
    created_at: _d(21), sent_at: _d(20), viewed_at: _d(18),
    line_items: [
      { kind: "material", description: "Roof membrane & primer (3-coat)", qty: 165, unit: "m2", unit_cost_cents: 1250 },
      { kind: "material", description: "Replacement tiles & pointing", qty: 1, unit: "ea", unit_cost_cents: 42000 },
      { kind: "labour", description: "Pressure clean & prep", qty: 12, unit: "hr", unit_cost_cents: 9500 },
      { kind: "labour", description: "Spray application", qty: 20, unit: "hr", unit_cost_cents: 9500 },
    ],
    inclusions: ["Supply of all materials specified in this quote.", "Removal and lawful disposal of all roofing debris.", "Site left clean and tidy on completion."],
    exclusions: ["We are not responsible for electrical work.", "Existing roof falls are not corrected; we remove and replace to existing falls and capacity."],
    custom_clauses: [],
  },
  {
    id: "q3", quote_number: "Q-2026-0003", client_id: "c5", status: "sent",
    roof_type: "Strata — box gutter relining (x6 units)", valid_days: 30,
    show_breakdown: true, margin_pct: 16, gst_enabled: false,
    notes: "Reline failed box gutters across six terraced units. Single-ply membrane to all internal gutters and sumps.",
    created_at: _d(10), sent_at: _d(9),
    line_items: [
      { kind: "material", description: "TPO single-ply membrane", qty: 88, unit: "m2", unit_cost_cents: 5500 },
      { kind: "material", description: "Sumps, outlets & overflows", qty: 12, unit: "ea", unit_cost_cents: 9800 },
      { kind: "labour", description: "Strip & prepare gutters", qty: 30, unit: "hr", unit_cost_cents: 9500 },
      { kind: "labour", description: "Membrane welding & detailing", qty: 44, unit: "hr", unit_cost_cents: 9500 },
    ],
    inclusions: ["Supply of all materials specified in this quote.", "Removal and lawful disposal of all roofing debris.", "All work carried out to AS 1562.1 and manufacturer specifications."],
    exclusions: ["We are not responsible for structural or carpentry issues.", "Latent (pre-existing, concealed) conditions are excluded and, if found, will be quoted as a variation.", "Hydraulic/structural engineering, if required, must be engaged separately."],
    custom_clauses: [],
  },
];
